### ISSUE TITLE
There is UCL syntax that is IMHO clearer

### ISSUE THREAD

**Issue by hauleth** [kvark/ron#2]
https://github.com/hauleth/ucl-rs (my bindings to libucl written in C, maybe I rewrite it to Rust when I will have spare time).

I cannot find any other contact to you.

**Comment by kvark** [comment]
Thanks for the suggestion! This is the right place for it.
I found UCL lacking in several aspects:
  - *sugar*: there are multiple ways to define the same thing, which is not rusty
  - *implementation*: no standard serialization is implemented, so it's not a drop-in solution
  - *arrays*: too verbose and error-prone (not first-class citizens)
  - *maps*: being a core concept, they leave no way to specify a struct explicitly. It's not as bad as in JSON, since you could have a convention (use quoted keys for maps and non-quoted for struct fields), but it'd be even better to enforce the convention by the format itself.
